### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by Kreggenwinkel** [realvnc-labs/rport#1229]
**Describe the bug**
Hi guys, we are expecting temporary memory leaks on our port server installation.
What is interesting is that this problem does not occur every day.
Sometimes we have silence for days, then this problem occurs all day, or even only once or twice after restarts.

With journalctl -u rportd.service we see the following errors:

```Sep 11 13:20:13 rport_server.server rportd[27135]: 2023/09/11 13:20:13 http: panic serving 37.71.9.101:54482: runtime error: invalid memory address or nil pointer dereference
Sep 11 13:20:13 rport_server.server rportd[27135]: goroutine 854039 [running]:
Sep 11 13:20:13 rport_server.server rportd[27135]: net/http.(*conn).serve.func1()
Sep 11 13:20:13 rport_server.server rportd[27135]:         /opt/hostedtoolcache/go/1.19.4/x64/src/net/http/server.go:1850 +0xbf
Sep 11 13:20:13 rport_server.server rportd[27135]: panic({0x1012520, 0x19230c0})
Sep 11 13:20:13 rport_server.server rportd[27135]:         /opt/hostedtoolcache/go/1.19.4/x64/src/runtime/panic.go:890 +0x262
Sep 11 13:20:13 rport_server.server rportd[27135]: github.com/cloudradar-monitoring/rport/server.(*ClientListener).handleWebsocket(0xc000b8a0a0, {0x12dbaa8, 0xc06c548980}, 0x0?)
Sep 11 13:20:13 rport_server.server rportd[27135]:         /home/runner/work/rport/rport/server/client_listener.go:242 +0x4a8
Sep 11 13:20:13 rport_server.server rportd[27135]: github.com/cloudradar-monitoring/rport/server.(*ClientListener).handleClient(0xc000b8a0a0, {0x12dbaa8, 0xc06c548980}, 0xc098cce600)
Sep 11 13:20:13 rport_server.server rportd[27135]:         /home/runner/work/rport/rport/server/client_listener.go:183 +0x165
Sep 11 13:20:13 rport_server.server rportd[27135]: net/http.HandlerFunc.ServeHTTP(0xc098cce600?, {0x12dbaa8?, 0xc06c548980?}, 0xcb8c25?)
Sep 11 13:20:13 rport_server.server rportd[27135]:         /opt/hostedtoolcache/go/1.19.4/x64/src/net/http/server.go:2109 +0x2f
Sep 11 13:20:13 rport_server.server rportd[27135]: github.com/cloudradar-monitoring/rport/server/api/middleware.MaxBytes.func1({0x12dbaa8?, 0xc06c548980}, 0xc098cce600)
Sep 11 13:20:13 rport_server.server rportd[27135]:         /home/runner/work/rport/rport/server/api/middleware/maxbytes.go:15 +0x203
Sep 11 13:20:13 rport_server.server rportd[27135]: net/http.HandlerFunc.ServeHTTP(0xc098cce600?, {0x12dbaa8?, 0xc06c548980?}, 0x7abf01?)
Sep 11 13:20:13 rport_server.server rportd[27135]:         /opt/hostedtoolcache/go/1.19.4/x64/src/net/http/server.go:2109 +0x2f
Sep 11 13:20:13 rport_server.server rportd[27135]: github.com/cloudradar-monitoring/rport/share/security.RejectBannedIPs.func1.1({0x12dbaa8, 0xc06c548980}, 0x12dc768?)
Sep 11 13:20:13 rport_server.server rportd[27135]:         /home/runner/work/rport/rport/share/security/middleware.go:21 +0xa7
Sep 11 13:20:13 rport_server.server rportd[27135]: net/http.HandlerFunc.ServeHTTP(0x12dc768?, {0x12dbaa8?, 0xc06c548980?}, 0xc000f322d0?)
Sep 11 13:20:13 rport_server.server rportd[27135]:         /opt/hostedtoolcache/go/1.19.4/x64/src/net/http/server.go:2109 +0x2f
Sep 11 13:20:13 rport_server.server rportd[27135]: github.com/jpillora/requestlog.WrapWith.func1({0x12dc768?, 0xc08eb58ee0?}, 0x7f7df24305d0?)
Sep 11 13:20:13 rport_server.server rportd[27135]:         /home/runner/go/pkg/mod/github.com/jpillora/requestlog@v1.0.0/wrap.go:80 +0x62
Sep 11 13:20:13 rport_server.server rportd[27135]: net/http.HandlerFunc.ServeHTTP(0x0?, {0x12dc768?, 0xc08eb58ee0?}, 0x78530e?)
Sep 11 13:20:13 rport_server.server rportd[27135]:         /opt/hostedtoolcache/go/1.19.4/x64/src/net/http/server.go:2109 +0x2f
Sep 11 13:20:13 rport_server.server rportd[27135]: net/http.serverHandler.ServeHTTP({0xc096514bd0?}, {0x12dc768, 0xc08eb58ee0}, 0xc098cce600)
Sep 11 13:20:13 rport_server.server rportd[27135]:         /opt/hostedtoolcache/go/1.19.4/x64/src/net/http/server.go:2947 +0x30c
Sep 11 13:20:13 rport_server.server rportd[27135]: net/http.(*conn).serve(0xc080be4aa0, {0x12ddd70, 0xc000d4a0c0})
Sep 11 13:20:13 rport_server.server rportd[27135]:         /opt/hostedtoolcache/go/1.19.4/x64/src/net/http/server.go:1991 +0x607
Sep 11 13:20:13 rport_server.server rportd[27135]: created by net/http.(*Server).Serve
Sep 11 13:20:13 rport_server.server rportd[27135]:         /opt/hostedtoolcache/go/1.19.4/x64/src/net/http/server.go:3102 +0x4db
Sep 11 13:20:39 rport_server.server rportd[27135]: 2023/09/11 13:20:39 http: panic serving 109.43.113.212:23345: runtime error: invalid memory address or nil pointer dereference
Sep 11 13:20:39 rport_server.server rportd[27135]: goroutine 945399 [running]:
Sep 11 13:20:39 rport_server.server rportd[27135]: net/http.(*conn).serve.func1()
Sep 11 13:20:39 rport_server.server rportd[27135]:         /opt/hostedtoolcache/go/1.19.4/x64/src/net/http/server.go:1850 +0xbf
Sep 11 13:20:39 rport_server.server rportd[27135]: panic({0x1012520, 0x19230c0})
Sep 11 13:20:39 rport_server.server rportd[27135]:         /opt/hostedtoolcache/go/1.19.4/x64/src/runtime/panic.go:890 +0x262
```

We also see the memory problems in our monitoring:
![image](https://github.com/realvnc-labs/rport/assets/22314012/0bdb4711-f408-47d0-9ab5-a000afdf0b0d)

And when we try to access a device via the rport CLI we get the following error:
`FATAL: failed to send request: websocket: close 1006 (abnormal closure): unexpected EOF`

**Environment**

Rport Server: 
Clients connected:
828
Clients disconnected:
367
Version:
0.9.6

Frontend:
Version:
rport-frontend-0.9.5-build-1131

* RPort version
* OS details (Linux distribution, and version or Windows version)  - Red Hat Enterprise Linux release 8.8 (Ootpa)
* Is rportd running inside a docker container?  - No
* Are you using a reverse proxy? If yes, which one?  - No

any idea what could be causing these memory leaks? Since they only occur sporadically it is quite difficult to react to them.

**Comment by Kreggenwinkel** [comment]
Hi @thorstenkramm, 
we are using your provides tar.gz from the Releases. 
Yes this is the monitoring of the whole host, but the consumption ist only by the rportd service.

**Comment by thorstenkramm** [comment]
@Kreggenwinkel 
Do you mind [updating the rport server](https://kb.rport.io/digging-deeper/server-maintenance/updating-rport) to the latest version 0.9.12?
This version contains many stability fixes and improved memory management.
